# Generated by Django 6.0.6 on 2026-06-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Appointment',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
